openapi: "3.0.0"
info:
    title: Football League Data Api's
    description: Football Api that include the main data for the Premier league and La Liga
    termsOfService: http://example.com/terms/
    contact:
      name: Scadip API Team
      url: http://scadip.com/support
      email: apiteam@scadip.com
    license:
      name: MIT
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.0
servers:
  - url: http://localhost:9000/apirest
paths:
    /premier/{leagueId}/matchs:
      get:
        summary: List all football games in the history of the selected league
        operationId: getMatchGame
        tags:
          - premier
        parameters:
          - name: leagueId
            in: path
            required: true
            schema:
              type: string
              enum: [PRML, LIGA]
            description: >
              Sort order:
               * `PRML` - English League, Premier League
               * `LIGA` - Spanish League, La Liga
        responses:
          '200':
            description: All games matchs to a valid request.
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Matchs"
          '403':
            description: The request contain a Wrong Content-type in its header.
          '404':
            description: Service is Not available.

    /premier/{leagueId}/season/{seasonId}/matchs:
       get:
         summary: List all football games of the selected league in an specific season
         operationId: getMatchGameSeason
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: seasonId
             in: path
             required: true
             schema:
               type: string
             description: >
               Format for the seasonId, example:
                * `For request season 2013/2014` seasonId = 2013-14
                * `For request season 2016/2017` seasonId = 2016-17
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/rangedates/matchs:
       get:
         summary: List all football games of the selected league in an specific range of date
         operationId: getMatchGameRangeDates
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: startingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation start date, example:
                * `For 20 February 2014` startingDate = 2014-02-20
           - name: endingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation ending date, example:
                * this value must be greater than or equal to "starting date"
                * `For 20 February 2014` startingDate = 2014-02-20
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/team/{teamId}/rangedates/matchs:
       get:
         summary: List all football games of the selected league in an specific range of date for an specific team
         operationId: getMatchGameHomeAwayRangeDates
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: startingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation start date, example:
                * `For request season 2013/2014` seasonId = 2013-14
           - name: endingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation ending date, example:
                * `For request season 2013/2014` seasonId = 2013-14
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/team/{teamId}/season/{seasonId}/matchs:
       get:
         summary: List all football games of the selected league in an specific season for an specific team
         operationId: getMatchGameHomeAwaySeason
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: seasonId
             in: path
             required: true
             schema:
               type: string
             description: >
               Format for the seasonId, example:
                * `For request season 2013/2014` seasonId = 2013-14
                * `For request season 2016/2017` seasonId = 2016-17
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/hometeam/{teamId}/rangedates/matchs:
       get:
         summary: List all match of an specific Team when is HOMETEAM in an specific league per range of date
         operationId: getMatchGameHomeRangeDates
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: startingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation start date, example:
                * `For request season 2013/2014` seasonId = 2013-14
           - name: endingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation ending date, example:
                * `For request season 2013/2014` seasonId = 2013-14
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/hometeam/{teamId}/season/{seasonId}/matchs:
       get:
         summary: List all match of an specific Team when is HOMETEAM in an specific league in an specific season
         operationId: getMatchGameHomeSeason
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: seasonId
             in: path
             required: true
             schema:
               type: string
             description: >
               Format for the seasonId, example:
                * `For request season 2013/2014` seasonId = 2013-14
                * `For request season 2016/2017` seasonId = 2016-17
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.
    /premier/{leagueId}/awayteam/{teamId}/rangedates/matchs:
       get:
         summary: List all match of an specific Team when is AWAYTEAM in an specific league per range of date
         operationId: getMatchGameAwayRangeDates
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: startingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation start date, example:
                * `For request season 2013/2014` seasonId = 2013-14
           - name: endingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation ending date, example:
                * `For request season 2013/2014` seasonId = 2013-14
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/awayteam/{teamId}/season/{seasonId}/matchs:
       get:
         summary: List all match of an specific Team when is AWAYTEAM in an specific league and in an specific season
         operationId: getMatchGameAwaySeason
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: teamId
             in: path
             required: true
             schema:
               type: string
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: seasonId
             in: path
             required: true
             schema:
               type: string
             description: >
               Format for the seasonId, example:
                * `For request season 2013/2014` seasonId = 2013-14
                * `For request season 2016/2017` seasonId = 2016-17
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Matchs"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/season/{seasonId}/scoreplayer:
       get:
         summary: List scoreplayer per season in an specific league
         operationId: getMatchGameScorerPlayerSeason
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: seasonId
             in: path
             required: true
             schema:
               type: string
             description: >
               Format for the seasonId, example:
                * `For request season 2013/2014` seasonId = 2013-14
                * `For request season 2016/2017` seasonId = 2016-17
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/PlayerStatsList"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

    /premier/{leagueId}/rangedates/scoreplayer:
       get:
         summary: List score player in an specific league in a range of date
         operationId: getMatchGameScorerPlayerRangeDates
         tags:
           - premier
         parameters:
           - name: leagueId
             in: path
             required: true
             schema:
               type: string
               enum: [PRML, LIGA]
             description: >
               Select the preferred league:
                * `PRML` - English League, Premier League
                * `LIGA` - Spanish League, La Liga
           - name: startingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation start date, example:
                * `For request season 2013/2014` seasonId = 2013-14
           - name: endingDate
             in: query
             required: true
             schema:
               type: string
               format: date
             description: >
               Date format for calculation ending date, example:
                * `For request season 2013/2014` seasonId = 2013-14
         responses:
           '200':
             description: All games matchs to a valid request.
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/PlayerStatsList"
           '403':
             description: The request contain a Wrong Content-type in its header.
           '404':
             description: Service is Not available.

components:
  schemas:
    Matchs:
      type: array
      items:
        $ref: "#/components/schemas/Match"
    Match:
      type: object
      properties:
        hometeam:
          $ref: "#/components/schemas/Team"
        awayteam:
          $ref: "#/components/schemas/Team"
        date:
          type: string
          format: date-time
        season:
          type: string
    PlayerStatsList:
      type: array
      items:
        $ref: "#/components/schemas/PlayerStats"
    Team:
      type: object
      properties:
        name:
          type: string
        goals:
          type: integer
          format: int32
        goalsPlayer:
          $ref: "#/components/schemas/GoalsPlayer"
    MinuteOfGoal:
      type: object
      properties:
        minuteGoal:
          type: string
    ListOfGoals:
      type: array
      items:
        $ref: "#/components/schemas/MinuteOfGoal"
    GoalsPlayer:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/ListOfGoals"
    PlayerStats:
      type: object
      properties:
        teamPlayer:
          type: string
        namePlayer:
          type: string
        goals:
          type: integer
          format: int32